name: C++ Workflow
on: push

env:
  BUILD_TYPE: "RELEASE"

jobs:
  clang-format:
    name: Clang Format
    runs-on: ubuntu-latest
    container: andersonjwan/clang-extra-tools:15.0.6
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clang Format Version
        run: clang-format --version
      - name: Run Clang Formatter Check
        run: find ./ -type f -iname *.cpp -or -iname *.hpp | xargs clang-format --Werror --dry-run --verbose --style=file
  cppcheck:
    name: Cppcheck
    runs-on: ubuntu-latest
    container: andersonjwan/cppcheck:2.9
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print Working Directory
        run: pwd
      - name: List GitHub Workspace
        run: ls ${{ github.workspace }}
      - name: Run Cppcheck
        run: cppcheck --enable=all --error-exitcode=2 --std=c++20 ./
  build:
    name: Compile
    runs-on: ubuntu-latest
    container: andersonjwan/cmake:3.25.1
    needs: [clang-format, cppcheck]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure & Generate Project Files
        run: cmake -B build/ -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build Project Files
        run: cmake --build build/ --config ${{env.BUILD_TYPE}}
